### ISSUE TITLE
Amplitude capture while speechSynthesis.speaking ?

### ISSUE THREAD

**Issue by mandymozart** [mdn/web-speech-api#10]
Hello, 

I am trying to build an avatar expressing a more human approach to the feedback.

We have been using a similar approach in Android and iOS with our latest app.
https://vimeo.com/106971829 <-- for example this one uses the audio input to animate x/y axis of our mouth animation

Thank you.

**Comment by ctsstc** [comment]
You probably will not see this as I'm not seeing it in the [W3 specs](https://dvcs.w3.org/hg/speech-api/raw-file/tip/webspeechapi.html)

You may have to go with another method such as recording the audio and processing it. I'm not sure what other web native APIs are available for recording, and if you're still wanting to use this API maybe only one can capture the mic at a time.

You could try another route such as trying to give characters/words specific mouth values, but that woudn't be anywhere near as interesting as what you've shown. 

Speech recognition may not be the correct route for what you're looking for. It sounds like you're looking for something with very little delay/processing whereas speech has plenty of delay and processing. I'm not certain that what you're looking for exists.

**Comment by schalkneethling** [comment]
Hey @mandymozart! Thank you for opening this issue. We are combining some of our repositories to enable us to triage pull requests and issues more effectively. Therefore, this specific repository will be merged into the more prominent [dom-examples](https://github.com/mdn/dom-examples) repository. Please open a new issue if you still feel that this issue is relevant. Thank you.
