### ISSUE TITLE
About manage the queue

### ISSUE THREAD

**Issue by sidkasundra** [mdn/web-speech-api#24]
How can we manage the queue..
Suppose i have one string that is speaking at that time i pause that speech and select the other string for speak but currently they complete the first speech then after they speak the 2nd one.
I try to pause the 1st one for some time(not cancel the speech) and speak 2nd one..
Help me to figure it out

**Comment by schalkneethling** [comment]
Hey @sidkasundra! Thank you for opening this issue. For general questions like this one, we would recommend either StackOverflow, or our [Discourse community space](https://discourse.mozilla.org/c/mdn/236). We are combining some of our repositories to enable us to triage pull requests and issues more effectively. Therefore, this specific repository will be merged into the more prominent [dom-examples](https://github.com/mdn/dom-examples) repository. Please open a new issue if you still feel that this issue is relevant. Thank you.
