### ISSUE TITLE
Firefox 59 - nothing works

### ISSUE THREAD

**Issue by stutteringp0et** [mdn/web-speech-api#25]
ReferenceError: webkitSpeechRecognition is not defined[Learn More] script.js:1:5

I've tried all of the demos - and nothing works.  All I get is this error.  I've set media.webspeech.recognition.enable to true - restarted the browser (just in case) and still nothing but this error.

**Comment by chrisdavidmills** [comment]
The recognition stuff has not worked in Firefox for a while. We only ever really had it working in Firefox OS, back in those days. The synthesis stuff should work though.

I think work is ongoing at the moment to add in recognition support again.

**Comment by 1der1** [comment]
There seems to be no way to get more than the mediocre Microsoft "Anna" voice with Firefox.

Yes, I tried speechSynthesis.onvoiceschanged, but all the demos using it fail as well. 

I am using Firefox Quantum, 60.0.2 (64-bit)  (select doesn't work in the Firefox About box...)

**Comment by christian212519** [comment]
Hey guys, apologies for not getting back to you sooner.  Basically, the reason your not able to access your microphone is due to a security issues mostly all browsers enforce.  That being, if you try to run a file wile the initial extension file:///, it will refuse to give access to your microphone, Hence, this program will never work in that instance.  However, if you do want to see this program work, simply copy and paste the html, js, and css into your preferred IDE and run it from there.  It will operate under a local host which your browser will accept and give access to your microphone.  Hope this helps!

**Comment by Phe0nix** [comment]
Only working on chrome till now.
Other browsers fails to do that.
On opera, Speech Recognition is supported but still not working.

**Comment by schalkneethling** [comment]
Hey @stutteringp0et! Thank you for opening this issue. We are combining some of our repositories to enable us to triage pull requests and issues more effectively. Therefore, this specific repository will be merged into the more prominent [dom-examples](https://github.com/mdn/dom-examples) repository. Please open a new issue if you still feel that this issue is relevant. Thank you.
