### ISSUE TITLE
Undefined variable assignment 

### ISSUE THREAD

**Issue by kumavis** [mdn/web-speech-api#35]
https://github.com/mdn/web-speech-api/blob/6147019c096cf6b188ef9a3df1214be03d2ffc3f/speak-easy-synthesis/script.js#L18

**Comment by etisdew** [comment]
This information seems terribly out of date for firefox compatibility when the m in mdn means mozilla. Question for the maintainer, where is the discussion on this topic? @kumavis What browser and OS? Technically it is assigned above as a closure but the intrinsic fails to undefined correct? Blame should fall to line 1.

**Comment by chrisdavidmills** [comment]
What browser is this demo failing in? I am still seeing it working in both Fx and Chrome

**Comment by etisdew** [comment]
I'm personally trying to go the firefox pocket-sphynx route not only chasing a lead at this point. Any information on finding firefox compatibility specificly? Can confirm failing firefox 67 arch gnu/linux ^5.0 but I feel like there is a browser recompilation in the way at this point or something roundabout. What is your recommended course of action achieving a cross browser solution?

**Comment by schalkneethling** [comment]
Hey @kumavis! Thank you for opening this issue. We are combining some of our repositories to enable us to triage pull requests and issues more effectively. Therefore, this specific repository will be merged into the more prominent [dom-examples](https://github.com/mdn/dom-examples) repository. Please open a new issue if you still feel that this issue is relevant. Thank you.
