### ISSUE TITLE
voiceSelect.selectedOptions[0] is undefined

### ISSUE THREAD

**Issue by Mte90** [mdn/web-speech-api#4]
On firefox 49 i get `voiceSelect.selectedOptions[0] is undefined` http://mdn.github.io/web-speech-api/speak-easy-synthesis/

**Comment by clemens-tolboom** [comment]
This is probably fixed by PR #5

**Comment by LoLei** [comment]
I'm getting the same in Firefox 76.0.1.

The drop-down menu is empty. When clicking play this errors shows up. I guess because I could not select a voice.

**Comment by schalkneethling** [comment]
Hey @Mte90 and @LoLei! Thank you for opening and commenting on this issue. We are combining some of our repositories to enable us to triage pull requests and issues more effectively. Therefore, this specific repository will be merged into the more prominent [dom-examples](https://github.com/mdn/dom-examples) repository. Please open a new issue if you still feel that this issue is relevant. Thank you.
